# Generated by Django 5.1.4 on 2025-01-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_userstory_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
