# Generated by Django 5.1.4 on 2025-01-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Companie',
            new_name='companie',
        ),
    ]
